### ISSUE TITLE
Add preservation to pairing logic of operators

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#31] opened 2019-11-26 21:13 UTC
Right now using only patient id and bait set to match tumor with normals; add preservation

**Comment by nikhil** [comment] 2020-01-16 16:09
@stevekm can work on this after we import pooled normals

**Comment by nikhil** [comment] 2020-01-16 16:57
possible duplicate of https://github.com/mskcc/beagle/issues/57

**Closed** 2020-03-19 15:23 UTC
