### ISSUE TITLE
Restart does not resume run

### ISSUE THREAD

**Issue by nikhil** [mskcc/beagle#762] opened 2021-03-19 15:18 UTC
I tried to restart operator run: b503e4a2-4137-4f8f-8484-7f3afcfccfa0 and its run (0343affe-8c09-4005-9b3e-ed3a7c3df49a) has a valid jobstore.

```{
  "runs_restarted": [
    "b7455885-bd16-4a81-9b1a-5cb36d5bdd54"
  ],
  "runs_copied": []
}
```

but ridgeback shows the new run: (http://voyager:5003/v0/jobs/987c8df9-57f5-4570-b4b1-8de44bc2c160/)
has 
```
"resume_job_store_location": null,
```

**Comment by nikhil** [comment] 2021-03-19 15:21
The run also gives a strange error 
```
cwltool.errors.WorkflowException: ../../work/ci/beagle/work/987c8df9-57f5-4570-b4b1-8de44bc2c160/pluto-cwl/cwl/workflow_with_facets.cwl:259:3: Missing req    uired input parameter 'IMPACT_gene_list'
```

and the command does not have --restart or the original jobstore

```
cwltoil --singularity --coalesceStatusCalls --logFile toil_log.log --batchSystem lsf --disable-user-provenance --disable-host-prov    enance --stats --debug --disableCaching --preserve-environment PATH TMPDIR TOIL_LSF_ARGS SINGULARITY_PULLDIR SINGULARITY_CACHEDIR PWD SINGULARITY_DOCKER_U    SERNAME SINGULARITY_DOCKER_PASSWORD --defaultMemory 8G --maxCores 16 --maxDisk 128G --maxMemory 256G --not-strict --realTimeLogging --jobStore /work/ci/be    agle/job-store/987c8df9-57f5-4570-b4b1-8de44bc2c160 --tmpdir-prefix /work/ci/beagle/tmp/987c8df9-57f5-4570-b4b1-8de44bc2c160 --workDir /work/ci/beagle/wor    k/987c8df9-57f5-4570-b4b1-8de44bc2c160 --outdir /juno/res/ci/voyager/b7455885-bd16-4a81-9b1a-5cb36d5bdd54 --maxLocalJobs 500 /work/ci/beagle/work/987c8df9    -57f5-4570-b4b1-8de44bc2c160/pluto-cwl/cwl/workflow_with_facets.cwl /work/ci/beagle/work/987c8df9-57f5-4570-b4b1-8de44bc2c160/input.json
```

**Comment by ionox0** [comment] 2021-03-22 17:47
I just experienced this as well, the strange error you see is because the inputs.json is empty. 

I also noticed this in the logs:
```
[2021-03-22 13:13:02,262: INFO/ForkPoolWorker-63] Failed to resume runs not equal
[2021-03-22 13:13:02,267: INFO/ForkPoolWorker-63] Job bae62dbc-be4c-4e4e-9199-419ad4b45d50 ready for submitting
[2021-03-22 13:13:02,296: INFO/ForkPoolWorker-63] Job bae62dbc-be4c-4e4e-9199-419ad4b45d50 successfully submitted with id:3cf32d6e-3407-4556-bc1a-131251b689c3
```

So somehow the inputs for the original Run and the restarted Run are not the same:


```
        if run1.equal(run2):
            logger.info("Resuming run: %s with execution id: %s" % (str(run.resume), str(run2.run_obj.execution_id)))
            resume = str(run2.run_obj.execution_id)
        else:
            logger.info("Failed to resume runs not equal")
```

**Comment by ionox0** [comment] 2021-03-22 18:01
I looked at the 2 runs in the shell and it turns out that the restarted run doesn't have any input ports associated with it:
```
In [5]: from runner.run.objects.run_object import RunObject

In [6]: run1 = RunObject.from_db("bae62dbc-be4c-4e4e-9199-419ad4b45d50")

In [7]: run2 = RunObject.from_db("7f264fb8-65c7-473a-a223-0399d414cff6")

In [8]: run1.equal(run2)
Out[8]: False

In [9]: run1.inputs
Out[9]: []

In [10]: run2.inputs
Out[10]:
[(PORT) 15d2beb1-d855-407e-bba2-3e106f3a723b: Name: project_name Type: INPUT,
 (PORT) 810aa1ff-f93c-46e2-ae9f-63bcaa35d788: Name: sv_tumor_bams Type: INPUT,
 (PORT) 9fb81508-d517-4181-9587-ddfceb2464de: Name: sv_normal_bam Type: INPUT,
 (PORT) 74a28a38-64d5-4428-b876-a481af65de49: Name: version Type: INPUT,
 (PORT) f6433d38-87ac-463b-a0f6-6fcd637515c0: Name: sv_sample_id Type: INPUT,
 (PORT) 57ea0b1c-e144-41f1-b248-e7a686e26ff9: Name: sv_run_tools Type: INPUT,
 (PORT) 9202051f-074f-43c7-983d-7606ae565365: Name: ref_fasta Type: INPUT]
```

There might be something wrong with this code that is supposed to copy the input ports:
```
            # Copy over the input / output ports from the original Run
            ports = r.port_set.all()
            for p in ports:
                files = p.files.all()
                p.pk = None
                p.run_id = r.pk
                p.save()
                p.files.add(*files)
```

**Comment by ionox0** [comment] 2021-03-22 18:09
Ah, the problem is that `r.port_set.all()` refers to the *new* run, not the original run, so there are no Ports to be found:
```
            # Copy over the input / output ports from the original Run
            ports = r.port_set.all() # <-- "r" is the new run...
            for p in ports:
                files = p.files.all()
                p.pk = None
                p.run_id = r.pk
                p.save()
                p.files.add(*files)
```

I think this should be:
```
            # Copy over the input / output ports from the original Run
            original_run = Run.objects.get(original_run_id)
            ports = original_run.port_set.all()
            for p in ports:
                files = p.files.all()
                p.pk = None
                p.run_id = r.pk
                p.save()
                p.files.add(*files)
```

I'll push a fix

**Comment by allanbolipata** [comment] 2021-03-23 15:18
#767 fixes this; closing.

**Closed by allanbolipata** 2021-03-23 15:18 UTC
